driver: sql
database:
  driver: "postgres"
  url: "postgres://user:password@localhost:5432/dbname?sslmode=disable"
  table: "users"
  key_column: "email"
  column_names:
    - "email"
    - "handle"
    - "name"
  template: configs/sql/sql.gotempl
